
ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]
ifndef::imagesdir[:imagesdir: ../Img]


= ObjectScript 常用命令中文速查 +

=== 所有在WebTerminal中的ObjectScript命令大小写不敏感 SET / Set / set 均一样 +

=== 但是变量名和其他的如SQL命令依然大小写敏感 +

=== ObjectScript自带Python支持同时自身语法也一定程度上类似Python +

=== ObjectScript 变量对变量类型敏感 属于 Typeless Language +

{nbsp} +

==== 0.注释需要在 任意空白字符 后接  //  双正斜杠 +

==== 演算符优先级 Operator Precedence +
=== 和其他语言完全不同，采用严格的从左到右顺序 +
----
 WRITE "1 + 2 * 3 = ", 1 + 2 * 3,!  // returns 9
 WRITE "2 * 3 + 1 = ", 2 * 3 + 1,!  // returns 7
 WRITE "1 + (2 * 3) = ", 1 + (2 * 3),!  // returns 7
 WRITE "2 * (3 + 1) = ", 2 * (3 + 1),!  // returns 8
----
----
SET Value = (4 + 7 > 6 + 6) // returns 7
WRITE Value
----


==== 1.set A = B +
赋B值 给变量A（如果A变量不存在，则同时声明A变量 

==== 2.write A +
在当前界面打印 变量A (部分场合可能为保存 +
在write中 ! 惊叹号表示下一行 +
常写为 write A,! +

==== 3.kill A +
删除 变量A

==== 4.逻辑代码 +

==== while循环 +
----
 SET x=1
   WHILE x<10 {
      WRITE !," Looping",x
      SET x=x+1
   } //打印 Looping 1-9
----

==== if语句 +
此处还展示了 Quit 和 Break "S" 语句的不同，建议多实验几次，仔细观察
----
SET y=$RANDOM(10)   
IF y#2=0 {WRITE y," is even",!   
          QUIT     
          WRITE "不会打出来",!}   
          
ELSE {    WRITE y," is odd",!    
          break "S"     
          WRITE "Great!打出来了",!}   

WRITE "QUIT out of the IF",!
----

==== 标准for循环 +
此处类似C++/JAVA/Python等传统语言的用法 +
实际for的应用方法十分多变，恕篇幅原因不在此赘述。 +
参考： https://docs.intersystems.com/iris20212/csp/docbook/DocBook.UI.Page.cls?KEY=RCOS_cfor[EN_for语句详细使用说明] +
----
FOR index=1:1:10 {WRITE index,!} // 打印1-10 （会打印10
----

==== 5.Try Catch处理异常 +
同JAVA的异常处理逻辑 同时可以接受Throw
----
 TRY {
      protected statements //受保护代码
 } CATCH [ErrorHandle] {
      error statements //异常处理打码
 }
 further statements //后续其他代码,默认情况下会继续执行
----

----
TRY { WRITE "Here my method generates an error",! throw  }  catch {WRITE "Catched"} //TRY-Catch实验代码，无实际应用
----
==== 6.String 类型操作 连接 a b 这两个String +
----
SET a = "Inter"
SET b = "Systems"
SET string = a_b  //连接 a b 
WRITE string
----
 
==== 7.让用户输入字符串 READ 命令
其中 +
# 表示 新的屏幕 类似 window命令行中cls 或 Linux中的 Ctrl+L +
! 表示 下一行 类似 "\n" +
?7 表示 在第七个空格处
----
READ #!!,"Please enter",!,"your name: ",x,"THANK YOU"
----

==== 8. "?" 问号 趋势匹配 Pattern Matching 演算符 - 2018的老版文档 + 
https://docs.intersystems.com/latest/csp/docbook/DocBook.UI.Page.cls?KEY=TCOS_Pattern1[EN_趋势匹配演算符_对照] +
https://docs.intersystems.com/latest/csp/docbook/DocBook.UI.Page.cls?KEY=TCOS_Pattern2[EN_趋势匹配演算符_解释说明] +
美国SSN号码一般遵循 3个数字 + 一个“-中横杠” + 2个数字 + 一个“-中横杠” + 4个数字的规律 +

----
set ssn = "012-34-5678"

if ssn ? 3N1"-"2N1"-"4N write "valid"
----

所以 3N1"-" 这段代码实际上 + 
3N 代表需要3个数字 +
1"-" 代表需要一个中横杠 +

进行匹配 +

==== 9. ##class 关键字 类似 JAVA/C++ 中 Stactic +
每次新建 实例object 时，必须使用此关键字
----
SET expr = ##class(Person).%New()
----

= 官方资料 +
1. https://docs.intersystems.com/iris20212/csp/docbook/DocBook.UI.Page.cls?KEY=RCOS_COMMANDS[EN_ObjectScript详细文档] +
2. https://docs.intersystems.com/irislatest/csp/docbook/DocBook.UI.Page.cls?KEY=GORIENT_ch_cos#GORIENT_cos_commands_familiar[EN_常用ObjectScript命令速查] +
3. https://docs.intersystems.com/iris20212/csp/docbook/Doc.View.cls?KEY=GCOS_strings[EN_String相关运算符] +
4. https://docs.intersystems.com/iris20212/csp/docbook/Doc.View.cls?KEY=RCOS_cread#:~:text=!%20starts%20a%20new,a%20positive%20integer[EN_ObjectScript中特殊String字符] +


=== 以上


== 名词对照表
PlaceHolder : 暂时无中日版官方翻译 暂空
[options="header,footer" cols="s,s,s"]
|=======================
|中文|English|日本語

|=======================


    
